### ISSUE TITLE
Django 2.0 compatibility?

### ISSUE THREAD

**Issue by SebJansen** [valerymelou/django-active-link#2]
* Django Active Link version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by valerymelou** [comment]
I'll get to that. As soon as I have some free time.

**Comment by valerymelou** [comment]
Solved in the latest release in PyPI.
