### ISSUE TITLE
Reversing URLs with params

### ISSUE THREAD

**Issue by bartlomieju** [valerymelou/django-active-link#3]
Really cool package. However it lacks support for view names that take `args/kwargs`. It might be a good idea to implement it.

**Comment by valerymelou** [comment]
Thanks for filling this issue (and also providing a fix), I was off for a while).

Fixed in #4

**Comment by coler-j** [comment]
I had an issue using multiple URLs (in the case where there is a root menu and a detail view / sub menu), so I added a tests and handled the exception: https://github.com/valerymelou/django-active-link/pull/22

**Comment by valerymelou** [comment]
Wow thanks a lot for that. I'm having an issue for now with the Travis CI tests. I will fix it and merge your changes. Thanks again.
