### ISSUE TITLE
Deploy the django-active-link/pull/6 (Support or syntax)

### ISSUE THREAD

**Issue by paulovitin** [valerymelou/django-active-link#7]
Can you deploy the last version to pypi, please?

**Comment by valerymelou** [comment]
Hi! Sorry for the late response. It's already deployed there. What's the issue you are facing?

**Comment by paulovitin** [comment]
Thanks for answering, but no. The last PR https://github.com/valerymelou/django-active-link/pull/6 not deployed in pypi.

**Comment by valerymelou** [comment]
Sorry, I thought I did it days ago.
I just did it now https://pypi.org/project/django-active-link/0.1.5/
Thanks for pointing that out.
